server:
  port: 8083
spring:
  application:
    name: ApiGateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes[0]:
        id: UserService
        uri: lb://UserService
        predicates:
          - Path=/users/**, /auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    hostname: localhost
