server:
  port: 9090
spring:
  application:
    name: ApiGateway
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    hostname: localhost
