spring:
  application:
    name: MailSender
  kafka:
    prefix: mail-sender
    confirm-email: confirm-email
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    hostname: localhost
server:
  port: 0