spring:
  application:
    name: UserService
  datasource:
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microservices_2024_db
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    hostname: localhost
kafka:
  confirm-email: mail-sender.confirm-email
server:
  port: 0